# Generated by Django 4.2.7 on 2023-12-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='last_date',
            new_name='Task_Assign_Date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='details',
            new_name='Task_Description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='Task_Title',
        ),
    ]
