# Generated by Django 4.2.7 on 2023-12-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='Category_Name',
        ),
    ]
